Add solution to 7.11 task
t-pyrope/python-course pull request #2
Opened 2021-11-06 12:49 UTC by t-pyrope

This is a solution for the 'Loops' task

2021-11-18 12:48 UTC, svarnypetr requested changes
Zkuste se zamyslet, jak prepsat tu prvni ulohu bez dvojiho cykleni. Obecne je dobre se snazit nemit vnorene cykly.

2021-11-18 12:48 UTC, svarnypetr commented on python_loops.py
> +			print(value.capitalize())
Tady neni treba delat dvoji smycku. Dokazala byste to udelat bez te smycky na radku 40?

2021-11-18 12:48 UTC, svarnypetr commented on python_loops.py
> +	print("Sorry, we don't know such a name. Are you Czech at all?")
hehe

2021-11-18 12:48 UTC, svarnypetr commented on python_loops.py
> +for m in a:
Osobne bych zde pouzil jasnejsich jmen nez jen m a num, tak aby bylo jasne, jak se matice prochazi.

2021-11-18 12:48 UTC, svarnypetr commented on python_loops.py
> +shopping_list = list(set(shopping_list))
Zajimavy mechanismus jak zajistit jeden vyskyt :D Mozna lepsi by bylo jen pouzit `if`.

2021-11-18 12:48 UTC, svarnypetr commented on python_loops.py
> +pos = [i for i, letter in enumerate(string_list) if letter == 'A']
Velmi elegantni list comprehension!

2021-11-28 19:43 UTC, t-pyrope commented on python_loops.py
> +pos = [i for i, letter in enumerate(string_list) if letter == 'A']
Děkuji 🙏

2021-12-09 10:59 UTC, svarnypetr approved these changes
Super

2021-12-11 08:05 UTC, merged